- name: Set STAR globaly
  file:
    path: /usr/local/bin/STAR
    src: "{{ soft_dir }}/STAR-{{ version }}/bin/STAR"
    state: link
    owner: "{{ main_guy }}"

- name: Set picard globaly
  file:
    path: /usr/local/bin/picard
    src: "{{ soft_dir }}/picard-{{ version }}/bin/picard"
    state: link
    owner: "{{ main_guy }}"

