---

- name: Download FastQC
  get_url:
    url=http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v{{version}}.zip
    dest={{ source_dir }}/fastqc_v{{ version }}.zip

- name: Uncompress FastQC
  unarchive:
    src={{ source_dir }}/fastqc_v{{ version }}.zip
    dest={{ soft_dir }}
    copy=no

- name: Move FastQC to a version specific directory
  shell: mv {{ soft_dir }}/FastQC {{ soft_dir }}/FastQC-{{ version }}
  args:
    creates: "{{ soft_dir }}/FastQC-{{version}}/fastqc"

- file: path="{{ soft_dir }}/FastQC-{{ version }}/fastqc" mode="a+x"

- name: Set FastQC globaly throught /usr/bin/local
  become: "{{ slink_executable_to_user_local_bin }}"

  file:
    path: /usr/local/bin/fastqc
    src: "{{ soft_dir }}/FastQC-{{ version }}/fastqc"
    state: link
    owner: "{{ main_guy }}"
  when: slink_executable_to_user_local_bin

- name: Check for ~/.bashrc file
  stat: path={{ local_home }}/.bashrc
  register: check_bashrc

- name: Set FastQC globaly throught PATH new bashrc
  template:
    src: bashrc
    dest: "{{ local_home }}/.bashrc"
  when: not check_bashrc.stat.exists and not slink_executable_to_user_local_bin

- name: Set FastQC globaly throught PATH append to bashrc
  lineinfile:
    dest: "{{ local_home }}/.bashrc"
    line: "export PATH={{ soft_dir }}/{{ bin_dir }}:$PATH"
  when: check_bashrc.stat.exists and not slink_executable_to_user_local_bin

  tags: fastqc
