---

- name: Download FastQC
  get_url:
    url=http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v{{version}}.zip
    dest={{ source_dir }}/fastqc_v{{ version }}.zip

- name: Uncompress FastQC
  unarchive:
    src={{ source_dir }}/fastqc_v{{ version }}.zip
    dest={{ soft_dir }}
    copy=no

- name: Move FastQC to a version specific directory
  command: mv {{ soft_dir }}/FastQC {{ soft_dir }}/FastQC-{{ version }} creates={{ soft_dir }}/FastQC-{{ version }}

- file: path="{{ soft_dir }}/FastQC-{{ version }}/fastqc" mode="a+x"

#- name: Set STAR globaly
#  file:
#    path: /usr/local/bin/STAR
#    src: "{{ soft_dir }}/STAR-{{ version }}/bin/STAR"
#    state: link
#    owner: "{{ main_guy }}"
