---

- name: Download htslib
  get_url:
    url=https://github.com/samtools/htslib/archive/{{version}}.tar.gz
    dest={{source_dir}}/htslib-{{version}}.tar.gz

- name: Uncompress htslib
  unarchive: 
    src: "{{ source_dir }}/htslib-{{version}}.tar.gz"
    dest: "{{ source_dir }}"
    copy: no
    creates: "{{ source_dir }}/htslib-{{version}}/README"

- name: Build and Install htslib
  shell: cd {{ source_dir }}/htslib-{{version}}; make install prefix="{{ soft_dir }}/htslib-{{version}}"
  args:
    creates: "{{ soft_dir }}/htslib-{{version}}/bin/tabix"

  tags: htslib

- name: Symlink bgzip to /usr/local/bin
  become: "{{ slink_executable_to_user_local_bin }}"

  file:
    path: /usr/local/bin/bgzip
    src: "{{ soft_dir }}/htslib-{{ version }}/bin/bgzip"
    state: link
    owner: "{{ main_guy }}"
  when: slink_executable_to_user_local_bin

- name: Check for ~/.bashrc file
  stat: path={{ local_home }}/.bashrc
  register: check_bashrc

- name: Add htslib tools to users PATH in .bashrc
  lineinfile:
    dest: "{{ local_home }}/.bashrc"
    line: "export PATH={{ soft_dir }}/{{ bin_dir }}:$PATH"
  when: check_bashrc.stat.exists
