---

- name: Download htslib
  get_url:
    url=https://github.com/samtools/htslib/archive/{{version}}.tar.gz
    dest={{source_dir}}/htslib-{{version}}.tar.gz

- name: Uncompress htslib
  unarchive: 
    src: "{{ source_dir }}/htslib-{{version}}.tar.gz"
    dest: "{{ source_dir }}"
    copy: no
    creates: "{{ source_dir }}/htslib-{{version}}/README"

- name: Build and Install htslib
  shell: cd {{ source_dir }}/htslib-{{version}}; make
  args:
    creates: "{{ source_dir }}/htslib-{{version}}/bin/tabix"

  tags: htslib
