---

- include: STAR.yml version={{ star_version }}
- include: htslib.yml version={{ htslib_version }}
- include: samtools.yml version={{ samtools_version }}
- include: picard.yml version={{ picard_version }}
  #- include: fastqc.yml version={{ fastqc_version }}
- include: subread.yml version={{ subread_version }}
- include: rna-seqc.yml version={{ rnaseqc_version }}
- include: rnasik-pipe.yml version={{ sik_version }}

- name: display export message
  debug: msg="Run this command `export PATH={{ source_dir }}/RNAsik-pipe-{{ sik_version }}/src/:$PATH` to get RNAsik-pipe into your environment"
