---

- include: STAR.yml version=2.5.0c
- include: htslib.yml version=1.2
- include: samtools.yml version=1.2 htslib_version=1.2
- include: picard.yml version=1.129
- include: rna-seqc.yml version=1.1.8
- include: rnasik-pipe.yml version=1.2
- include: fastqc.yml tags=fastqc version=0.11.4
