---

- include: STAR.yml version=2.5.2a
- include: samtools.yml version=1.3 
- include: picard.yml version=2.4.1
- include: subread.yml version=1.5.0-p3
- include: rna-seqc.yml version=1.1.8
- include: rnasik-pipe.yml version=1.3.x
  #- include: fastqc.yml version=0.11.5
- include: fastqc.yml version=0.11.4
