---

- name: Download Picard
  get_url:
    url=https://github.com/broadinstitute/picard/releases/download/{{version}}/picard-tools-{{version}}.zip
    dest={{source_dir}}/picard-tools-{{version}}.zip

- name: Uncompress Picard
  unarchive: 
    src: "{{ source_dir }}/picard-tools-{{version}}.zip"
    dest: "{{ soft_dir }}"
    copy: no
    creates: "{{ soft_dir }}/picard-tools-{{version}}/picard.jar"

- file: dest="{{ soft_dir }}/picard-tools-{{version}}/bin" state=directory mode=0755

- name: Picard wrapper script
  template:
    src: java-wrapper.sh.j2
    dest: "{{ soft_dir }}/picard-tools-{{version}}/bin/picard"
    owner: "{{ main_guy }}"
    mode: 0755
  with_items:
    - { jar: '{{ soft_dir }}/picard-tools-{{version}}/picard.jar' }

- name: Set picard globaly
  file:
    path: /usr/local/bin/picard
    src: "{{ soft_dir }}/picard-{{ version }}/bin/picard"
    state: link
    owner: "{{ main_guy }}"

