---

- file:
    dest: "{{ source_dir }}/rna-seqc-{{ version }}"
    state: directory
    mode: 0755

  tags: get_rna-seqc 

- name: download RNA-SeQC
  get_url:
    url: "http://www.broadinstitute.org/cancer/cga/tools/rnaseqc/RNA-SeQC_v{{ version }}.jar"
    dest: "{{ source_dir }}/rna-seqc-{{ version }}"

  tags: get_rna-seqc 
