---

- file: dest="{{ soft_dir }}/RNA-SeQC_v{{version}}" state=directory mode=0755

- name: Download RNA-SeQC
  get_url:
    url=http://www.broadinstitute.org/cancer/cga/tools/rnaseqc/RNA-SeQC_v{{version}}.jar
    dest={{ soft_dir }}/RNA-SeQC_v{{version}}/RNA-SeQC_v{{version}}.jar

- name: RNA-SeQC wrapper script
  template:
    src: java-wrapper.sh.j2
    dest: "{{ soft_dir }}/RNA-SeQC_v{{version}}/rna-seqc"
    owner: "{{ main_guy }}"
    mode: 0755
  with_items:
    - { jar: '{{ soft_dir }}/RNA-SeQC_v{{version}}/RNA-SeQC_v{{version}}.jar' }

- name: Set RNA-SeQC globaly
  become: "{{ bool_var }}"

  file:
    path: /usr/local/bin/rna-seqc
    src: "{{ soft_dir }}/RNA-SeQC_v{{ version }}/rna-seqc"
    state: link
    owner: "{{ main_guy }}"
  when: "{{ bool_var }}"

  tags: rna-seqc
