---

# RNAsik-pipe installtion
- name: Git Clone RNAsik-pipe
  git: repo=https://github.com/monashbioinformaticsplatform/RNAsik-pipe.git
       dest={{ soft_dir }}/RNAsik-pipe-{{ version }}
       version={{ version }}
       update=no

- name: Set RNAsik-pipe globaly
  stat: path={{ local_home }}/.bashrc
  register: check_bashrc

- name: Set RNAsik-pipe globaly
  template:
    src: bashrc
    dest: link
    owner: "{{ local_home }}/.bashrc"
  when: not check_bashrc.stat.exists

- name: Seet RNAsik-pipe globaly
  lineinfile:
    dest: "{{ local_home }}/.bashrc"
    line: "export PATH={{ soft_dir }}/{{ bin_dir }}:$PATH"
#
#- name: Set RNAsik-pipe globaly
#  become: "{{ bool_var }}"
#
#  file:
#    path: /usr/local/bin/RNAsik-pipe
#    src: "{{ soft_dir }}/RNAsik-pipe-{{ version }}/src/RNAsik-pipe"
#    state: link
#    owner: "{{ main_guy }}"
#  when: "{{ bool_var }}"
#
#  tags: rnasik-pipe
