---

# RNAsik-pipe installtion
- name: Git Clone RNAsik-pipe
  git: repo=https://github.com/monashbioinformaticsplatform/RNAsik-pipe.git
       dest={{ soft_dir }}/{{ version }}
       version={{ version }}
       update=no
