---

# RNAsik-pipe installtion
- name: Git Clone RNAsik-pipe
  git: repo=https://github.com/monashbioinformaticsplatform/RNAsik-pipe.git
       dest={{ soft_dir }}/RNAsik-pipe-{{ version }}
       version={{ version }}
       update=no

- name: Set RNAsik-pipe globaly
  file:
    path: /usr/local/bin/RNAsik-pipe
    src: "{{ soft_dir }}/-RNAsik-pipe-{{ version }}/src/RNAsik-pipe"
    state: link
    owner: "{{ main_guy }}"
