---

# RNAsik-pipe installtion
- name: Git Clone RNAsik-pipe
  git: repo=https://github.com/monashbioinformaticsplatform/RNAsik-pipe.git
       dest={{ soft_dir }}/RNAsik-pipe-{{ version }}
       version={{ version }}
       update=no

- name: Check for ~/.bashrc file
  stat: path={{ local_home }}/.bashrc
  register: check_bashrc

- name: Set RNAsik-pipe globaly
  template:
    src: bashrc
    dest: "{{ local_home }}/.bashrc"
  when: not check_bashrc.stat.exists

- name: Set RNAsik-pipe globaly
  lineinfile:
    dest: "{{ local_home }}/.bashrc"
    line: "export PATH={{ soft_dir }}/{{ bin_dir }}:$PATH"
  when: check_bashrc.stat.exists

  tags: rnasik-pipe
