---

- name: Git Clone RNAsik-pipe
  git:
    repo: https://github.com/monashbioinformaticsplatform/RNAsik-pipe.git
    dest: "{{ source_dir }}/RNAsik-pipe-{{ sik_version }}"
    version: "{{ sik_version }}"
    update: no

  tags: sik

- name: Copy RNAsik-pipe configuration file
  template:
    src: sik.config
    dest: "{{ source_dir }}/RNAsik-pipe-{{ sik_version }}"

  tags: sik-config

- name: Edit path to bds interpreter
  lineinfile: 
    dest: "{{ source_dir }}/RNAsik-pipe-{{ sik_version }}/src/RNAsik-pipe"
    regexp: "/usr/bin/env bds"
    line: "#!{{ source_dir }}/BigDataScript-{{ bds_version }}/build/bds"

  tags: sik-config 
