---

- name: git clone samtools
  git:
    repo: https://github.com/samtools/samtools
    dest: "{{ source_dir }}/samtools-{{ version }}"
    version: "{{ version }}"
    # this should prevent git clone error if directory already exist
    update: no

  tags: get_samtools

- name: build samtools
  shell: cd {{ source_dir }}/samtools-{{ version }}; make install prefix={{ source_dir }}/samtools-{{ version }}
  #shell: cd {{ source_dir }}/samtools-{{ version }}; make install prefix={{ source_dir }}/samtools-{{version}} HTSDIR=../htslib-{{ htslib_version }}
  args:
    creates: "{{ source_dir }}/samtools-{{ version }}/bin/samtools"

  tags: build_samtools
