---

- name: Download STAR
  git: repo=https://github.com/alexdobin/STAR
       dest={{ source_dir }}/STAR-{{ version }}
       version={{version}}

- name: Install STAR
  shell: cd {{ source_dir }}/STAR-{{version}}/bin/Linux_x86_64_static; mkdir -p "{{ soft_dir }}/STAR-{{version}}/bin" && cp STAR STARlong "{{ soft_dir }}/STAR-{{version}}/bin"
  args:
    creates: "{{ soft_dir }}/STAR-{{version}}/bin/STAR"

- name: Set STAR globaly
  file:
    path: /usr/local/bin/STAR
    src: "{{ soft_dir }}/STAR-{{ version }}/bin/STAR"
    state: link
    owner: "{{ main_guy }}"
