---

- name: Download STAR
  git: repo=https://github.com/alexdobin/STAR
       dest={{ source_dir }}/STAR-{{ version }}
       version={{version}}

- name: Install STAR
  shell: cd {{ source_dir }}/STAR-{{version}}/bin/Linux_x86_64_static; mkdir -p "{{ soft_dir }}/STAR-{{version}}/bin" && cp STAR STARlong "{{ soft_dir }}/STAR-{{version}}/bin"
  args:
    creates: "{{ soft_dir }}/STAR-{{version}}/bin/STAR"

- file: dest="{{modules_dir}}/STAR" state=directory mode=0755

- name: STAR module definition
  template: 
    src: sw-module.lua.j2 
    dest: "{{ modules_dir }}/STAR/{{version}}.lua"
    owner: "{{ main_guy }}" 
    mode: 0644
  with_items:
    - dir: 'STAR-{{version}}'
      help_text: 'This module loads the STAR aligner'
      check: 

  tags: star
