---

- name: Download STAR
  git: repo=https://github.com/alexdobin/STAR
       dest={{ source_dir }}/STAR-{{ version }}
       version={{version}}

- name: Install STAR
  shell: cd {{ source_dir }}/STAR-{{version}}/bin/Linux_x86_64_static; mkdir -p "{{ soft_dir }}/STAR-{{version}}/bin" && cp STAR STARlong "{{ soft_dir }}/STAR-{{version}}/bin"
  args:
    creates: "{{ soft_dir }}/STAR-{{version}}/bin/STAR"

- name: Set STAR globaly throught /usr/local/bin
  become: "{{ slink_executable_to_user_local_bin }}"

  file:
    path: /usr/local/bin/STAR
    src: "{{ soft_dir }}/STAR-{{ version }}/bin/STAR"
    state: link
    owner: "{{ main_guy }}"
  when: slink_executable_to_user_local_bin

- name: Check for ~/.bashrc file
  stat: path={{ local_home }}/.bashrc
  register: check_bashrc

- name: Set STAR globaly throught PATH new bashrc
  template:
    src: bashrc
    dest: "{{ local_home }}/.bashrc"
  when: not check_bashrc.stat.exists and not slink_executable_to_user_local_bin

- name: Set STAR globaly throught PATH append to bashrc
  lineinfile:
    dest: "{{ local_home }}/.bashrc"
    line: "export PATH={{ soft_dir }}/{{ bin_dir }}:$PATH"
  when: check_bashrc.stat.exists and not slink_executable_to_user_local_bin

  tags: star
