---

# Installing BigDataScript
- name: Downloading BigDataScript
  git: repo=https://github.com/pcingola/BigDataScript.git
       dest={{ source_dir }}/BigDataScript-{{ version }}
       version={{ version }}

- name: Installing BigDataScript
  shell: cd {{ source_dir }}/BigDataScript-{{version}}/; ./scripts/install.sh

- file: dest="{{ soft_dir }}/BigDataScript-{{version}}" state=directory mode=0755

- name: Moving .bds file into global environment
  shell: mv $HOME/.bds "{{ soft_dir }}/BigDataScript-{{ version }}"
  args:
    creates: "{{ soft_dir }}/BigDataScript-{{ version }}/.bds/bds"
