---

# Installing BigDataScript
- name: Downloading BigDataScript
  git: repo=https://github.com/pcingola/BigDataScript.git
       dest={{ source_dir }}/BigDataScript-{{ version }}
       version={{ version }}

- name: Installing BigDataScript
  shell: cd {{ source_dir }}/BigDataScript-{{version}}/; ./scripts/install.sh

- name: Export to PATH
  environment:
          PATH: "{{ local_home }}/.bds":{{ ansible_env.PATH }}
