---
# This to install BigDataScript with all required dependencies

- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Installing Git, GoLang and Ant 
  apt: pkg={{item}} state=present
  with_items:
    - git
    - golang-go
    - ant
